#
###################################
# Site wide configuration
####################################
#
remote_theme : renyuanz/leonids
title: JihoKevin
email: jhshin925@gmail.com
description: ì„±ì¥ì— ë¯¸ì³ìˆëŠ” ì•ˆë“œë¡œì´ë“œ ê°œë°œì, ì‹ ì§€í˜¸ ì…ë‹ˆë‹¤ğŸ’ª
url: https://jihokevin.github.io/
baseurl : "https://jihokevin.github.io/"
keywords: ["blog", "jekyll"]


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: ì‹ ì§€í˜¸
  avatar: avatar.png
  job: "ì£¼ë‹ˆì–´ ì•ˆë“œë¡œì´ë“œ ê°œë°œì"
  bio: "ë°©ë¬¸í•´ì£¼ì…”ì„œ ê°ì‚¬í•©ë‹ˆë‹¤!ğŸ™‡ğŸ»â€â™‚ï¸"
  email: jhshin9250@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: JihoKevin
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: jiho_925
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

plugins : 
  - jekyll-sitemap
